/** @type {import('tailwindcss').Config} */
module.exports = {
    // Class-based so ModelEarth Ops can default to light and offer dark as a
    // user preference. A control room on a night shift is a real dark-mode
    // case; a Collector reading this at 11am in a bright office is not.
    darkMode: 'class',
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        // Severity chip and row classes are defined as literal strings in
        // lib/ops/severity.ts. Without this glob Tailwind never sees them, and
        // the dark variants in particular are silently dropped: the light
        // colours happen to be generated by other components, so the omission
        // looks fine until someone switches to dark and every severity row
        // paints its light background.
        './lib/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                background: '#0B0F19',
                foreground: '#FFFFFF',
                primary: '#2D82FF',
                'accent-start': '#2D82FF',
                'accent-end': '#22C1EE',
                'map-bg': '#0F1424',
            },
            fontFamily: {
                sans: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
                mono: ['var(--font-mono)', 'SF Mono', 'JetBrains Mono', 'Menlo', 'monospace'],
                display: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
            },
            boxShadow: {
                glow: '0 0 20px rgba(45, 130, 255, 0.3)',
                card: '0 8px 32px rgba(0, 0, 0, 0.4)',
            },
        },
    },
    plugins: [],
}
